config/routes.rb
Rails.application.routes.draw do
  get 'hoge/show',as:'hogehoge'
  root 'application#top'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  get 'questions/new/:id',to:'questions#new'
  get 'questions/index'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post 'answer/:id',to:'answers#create',as:'question_answer'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :questions
  resources :answers
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :response,  presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  
  def self.search(search) 
    if search
      where(['title LIKE ?', "%#{search}%"]) 
    else
      all 
    end
  end
    
  belongs_to :user, dependent: :destroy
  
  has_many :answers, through: :user
  #質問はユーザに紐づいた回答を持っている
  validates :title,  presence: true

  validates :content,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_secure_password
  has_many :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    
    def create
  @question = Question.find(params[:id])
  @answer = @question.answers.create(answer_params)
    if @answer.save
      flash[:success] = "回答を投稿しました。"
      redirect_to question_path(@question)
    else
      flash[:danger] = "回答に失敗しました。"
      redirect_to question_path(@question)
    end
    end
    
    private

  def answer_params
    params.require(:answer).permit(:response)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
	def top
	end

end

app/controllers/hoge_controller.rb
class HogeController < ApplicationController
  def show
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.order(id: "DESC").search(params[:search])
  end

  def new
    @question = Question.new
  end
  
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(id: "DESC")
    @testarray = [["レディース",001],["メンズ",002],["キッズ", 003]]
  end
  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      flash[:success] = "質問が完了しました。"
      redirect_to questions_index_path
    else
      flash[:danger] = "投稿に失敗しました。"
      redirect_to user_path(current_user)
    end
  end
  
  
private

  def question_params
    params.require(:question).permit(:title, :content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash[:danger] = "ログインに失敗しました。"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "新規登録"
      log_in @user
      redirect_to user_path(@user)
    else
      flash[:danger] = "失敗"
      render 'new'
    end
  end

  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
    end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def date_format(datetime)
    time_ago_in_words(datetime) + '前'
  end
end

app/helpers/hoge_helper.rb
module HogeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    
  def log_in(user)
    session[:user_id] = user.id
  end
		def current_user
			if session[:user_id]
				@current_user ||= User.find_by(id: session[:user_id])
			end
		end

		def logged_in?
			!current_user.nil?
		end

		def log_out
			session.delete(:user_id)
			@current_user = nil
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/top.html.erb
<div class="center">
<h1>みんなで質問しよう！</h1>
<%= link_to "アカウント作成", new_user_path, class: "btn btn-lg btn-primary" %>
<%= link_to "ログインはこちら", login_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/hoge/show.html.erb
  <div class="contract">
   <ul>
    <li>
     <label id="continuation" class="check label">
      <input checked class="radio_btn" type="radio" name="plan" value="1">
      <span>契約を継続する</span>
     </label>
    </li>
    <li>
     <label id="change" class="check label">
      <input checked class="radio_btn" type="radio" name="plan" value="2">
      <span>プラン変更する</span>
     </label>
    </li>
   </ul>
 </div>

<%= link_to "hoge", hogehoge_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OplDonichipl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h1>みんなの質問</h1>

<section class="container">
<div class="col-md-3 col-md-offset-8 ">
<p>タイトル検索</p>
<%= form_tag(questions_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :title => nil %>
<% end %>
</div>
</section>

<div class="center">
  <%= link_to "質問する", user_path(current_user), class: "btn btn-lg btn-primary" %>
  <% @questions.each do |question| %>
    <div class="title"><%=question.title%>/ForID<%=question.user_id%>さん</div>
    
    <div class="box">
      <%=question.content%>
      <div style="text-align: right"><%= link_to "この質問に回答する", question_path(question) %>
      <%=time_ago_in_words question.created_at %>前の質問</div>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<h1>質問投稿</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for( :questions, url: questions_path, method: :post) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.submit "質問する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<h1><%=@question.title%></h1>
<%binding.pry%>
<div class="center">
<%= link_to "みんなの質問を見る", questions_path,  class: "btn btn-lg btn-primary" %>

<div class="box">
      <%=@question.content%>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for( :answer, url: question_answer_path(@question.id), method: :post) do |f| %>

      <%= f.label :回答 %>
      <%= f.text_area :response, size:"20x10",class: 'form-control' %>

      <div style="text-align: left"><%= f.submit "回答する", class: "btn btn-primary" %></div>
    <% end %>
  </div>
</div>

<% @answers.each do |answer| %>
    <div class="box">
      <%=answer.response%>
      <div style="text-align: right">
      <%=time_ago_in_words answer.created_at %>前の回答
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>新規登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control'%>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: 'form-control'%>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control'%>

      <%= f.label :password_confirmation, "パスワード再確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control'%>

      <%= f.submit "新規作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>ようこそ！<%=@user.name%>さん</h1>
<div class="center">
<%= link_to "ログアウト", logout_path, method: :delete, class: "btn btn-lg btn-primary" %>
<%= link_to "みんなの質問を見る", questions_path,  class: "btn btn-lg btn-primary" %>
</div>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
    <%= form_for( :question, url: questions_path(@question), method: :post) do |f| %>

      <%= f.label :題名 %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :内容 %>
      <%= f.text_area :content, size:"20x10",class: 'form-control' %>

      <%= f.submit "質問する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>